feature: подключена база данных, добавлена функциональность создания …
TrapeznikovDanila/java-shareit pull request #3
Opened 2022-11-08 02:28 UTC by TrapeznikovDanila

…бронирований и отзывов

2022-11-08 19:51 UTC, sergeymamonov requested changes

2022-11-08 19:51 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (state == null || state.equals("ALL")) {
Посмотрите в сторону мапы, в ней будет статус и статус бронирования. Меняется только статус , а вся остальная часть у ретерна одинаковая. Но на рефакторинге не настаиваю.

2022-11-08 19:51 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            BookingResponseDto bookingResponseDto = BookingMapper.makeBookingResponseDto(booking);
Можно сразу вернуть результат вычисления, без создания промежуточной переменной.

2022-11-08 19:51 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if ((approved == true) && (booking.getStatus().equals(BookingStatus.APPROVED))) {
Можно просто писать if (approved && ...

2022-11-08 19:51 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (approved != null) {
Если approved == null, то дальше 62 строки код не пойдет.

2022-11-08 19:51 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
>      private HashMap<Long, Item> items = new HashMap<>();
Лучше определить на уровне интерфейса private Map<Long, Item> items

2022-11-08 19:51 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        ItemDto itemDto1 = getItemDtoById(itemId);
Лучше не использовать вот так число в названии переменной, потому что в данном случае не понятно, чем itemDto1 отличается от itemDto. Лучше замените число каким-то информативным словом. Исправить во всех местах, где встречается подобно.

2022-11-08 19:51 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<Booking> bookings1 = bookingRepository.findBookingsByBookerId(userId)
Переименовать.

2022-11-08 19:51 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
>      private HashMap<Long, User> users = new HashMap<>();
Используйте интерфейс.

2022-11-09 03:04 UTC, TrapeznikovDanila commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +            BookingResponseDto bookingResponseDto = BookingMapper.makeBookingResponseDto(booking);
Исправлено

2022-11-09 03:05 UTC, TrapeznikovDanila commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if ((approved == true) && (booking.getStatus().equals(BookingStatus.APPROVED))) {
Исправлено

2022-11-09 03:07 UTC, TrapeznikovDanila commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (approved != null) {
Исправлено

2022-11-09 03:11 UTC, TrapeznikovDanila commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
>      private HashMap<Long, Item> items = new HashMap<>();
Исправлено

2022-11-09 03:15 UTC, TrapeznikovDanila commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        ItemDto itemDto1 = getItemDtoById(itemId);
Исправлено

2022-11-09 03:16 UTC, TrapeznikovDanila commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<Booking> bookings1 = bookingRepository.findBookingsByBookerId(userId)
Исправлено

2022-11-09 03:17 UTC, TrapeznikovDanila commented on src/main/java/ru/practicum/shareit/user/UserRepositoryImpl.java
>      private HashMap<Long, User> users = new HashMap<>();
Исправлено

2022-11-10 05:57 UTC, TrapeznikovDanila commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        if (state == null || state.equals("ALL")) {
Исправлено

2022-11-11 13:55 UTC, sergeymamonov approved these changes

2022-11-13 14:18 UTC, merged