feature: приложение разделено на 2 сервиса: gateway и server. В gatew…
TrapeznikovDanila/java-shareit pull request #5
Opened 2022-12-07 12:38 UTC by TrapeznikovDanila

…ay вынесены все эндпоинты с которыми работают пользователи, server - содержит основную логику работы приложения. Также добавлены docker-compose.yml и Dockerfile, протестирована создание и работа из контейнера

2022-12-09 12:37 UTC, sergeymamonov requested changes
Класс BookingServiceImpl строка 42 можно проще if (item.getAvailable()) {}
Строки 89-94 зачем валидировать входные данные, если их уже провалидировали в gateway?
Строки 97-109 можно использовать switch, но это дело вкуса.
Класс ItemServiceImpl строка 152 можно проще .filter(item -> item.getAvailable())
"User not found" - ошибки лучше писать подробнее, пример "User with id = %s not found"

2022-12-09 12:37 UTC, sergeymamonov commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    }
Обратите внимание, что есть еще классы ошибок в этом пакете NotFoundException (404) и ValidationException (400). Поэтому лучше их тоже добавить в этот обработчик. Только NotFoundException нигде не используется и это логично, так как этот микросервис, не обращается к БД.

2022-12-09 12:37 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/exception/ValidationException.java
> +    public ValidationException(String message) {
А зачем валидировать данные, если их уже провалидировали в микросервисе gateway?

2022-12-09 12:37 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +//    List<Item> findItemByUserId(long userId);
В проекте не должно быть закомментированного кода.

2022-12-09 12:37 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>          for (Item item : items) {
Здесь делается запрос в цикле к БД. Выгрузите все нужные бронирования (1 запрос в БД) и работайте уже с бронированиями в своем приложении.

2022-12-10 13:28 UTC, TrapeznikovDanila commented on gateway/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +    }
Исправлено

2022-12-10 13:28 UTC, TrapeznikovDanila commented on server/src/main/java/ru/practicum/shareit/exception/ValidationException.java
> +    public ValidationException(String message) {
Валидация Dto полностью убрана из server

2022-12-10 13:28 UTC, TrapeznikovDanila commented on server/src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +//    List<Item> findItemByUserId(long userId);
Исправлено

2022-12-10 14:27 UTC, TrapeznikovDanila commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>          for (Item item : items) {
Исправлено

2022-12-11 05:18 UTC, sergeymamonov approved these changes

2022-12-11 05:18 UTC, sergeymamonov commented on server/src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .filter(b -> b.getStatus().equals(BookingStatus.APPROVED))
Лишний фильтр. Это условие можно перенести в запрос. Так получите меньше данных и БД сделает фильтрацию быстрее (так как в ней есть индексы, оптимизации и пр.).

2023-02-20 05:01 UTC, merged